### ISSUE TITLE
Rotate UV

### ISSUE THREAD

**Issue by sharktacos** [vidarn/ThunderLoom#10]
@petermcevoy Please add the ability to rotate the UVs (enhancement).  Pretty please!

This should happen _after_ the UV scale parameters.
This would make it possible to create knit as well as woven patterns:
![image](https://user-images.githubusercontent.com/23034637/30245597-fa421d34-9593-11e7-871a-d4c405938358.png)

**Comment by vidarn** [comment]
I will take a look at this, should be pretty straight-forward
