### ISSUE TITLE
Mult helper sliders for colors.

### ISSUE THREAD

**Issue by petermcevoy** [vidarn/ThunderLoom#2]
- Diffuse amount slider (mult)
Multiply diffuse color with this factor.

- ~~texture gamma text field~~
~~"texture gamma" field where the user could input the gamma to be used for all the colors. Currently they each need to be linearlized individually which takes a lot of work to set up. So having a single place to control this for all the diffuse colors would be very helpful.  The pseudo code would be "pow (color, texture_gamma)" so the default value of 1.0 would leave the colors unchanged, and a value of 2.2 would linearize all the diffuse colors from sRGB (2.2) to linear (1.0).~~

Suggested by Derek Flood.

**Comment by petermcevoy** [comment]
Added these params to core and added UI for Maya. 

221c4ccd84c39bf5dce985a14e446179e4713551

**Comment by petermcevoy** [comment]
We think these sliders do not really belong in the Shader. These manipulations might be better to do outside the shader, as a node in the node-graph. Just to keep the shader a bit focused on the task. Currently the diffuse slider and texture input it works just like the diffuse parameter in VRayMtl.

**Comment by sharktacos** [comment]
Maya 2017 color management makes having the texture gamma unnecessary. So I agree the texture gamma should not be included in the shader. 

It would be nice to have a diffuse amount slider though, just like in a VRayMtl. You say "Currently the diffuse slider and texture input it works just like the diffuse parameter in VRayMtl" so does that mean the diffuse amount slider has been implemented?

**Comment by petermcevoy** [comment]
Forgive me, again not very familiar with Maya, so I am probably missing something... But looking at the VRayMtl node in Maya, I can not see a multiplier/amount slider? Except the slider at Diffuse Color, which gets disabled if we link a texture (this functionality we do have). 

![screenshot 2017-09-04 17 14 16](https://user-images.githubusercontent.com/116268/30040035-ad4cd31a-91d9-11e7-9360-4c604fa65d6e.png)

![screenshot 2017-09-05 01 31 34](https://user-images.githubusercontent.com/116268/30040056-052b3fd6-91da-11e7-9fe7-d4e0e97f61de.png)

**Comment by sharktacos** [comment]
@petermcevoy,

 The Properties Editor you posted above is not showing all of the attributes in the VrayMtl, which is admittedly confusing. To see all the attributes you need to view the shader in Maya's Attribute Editor. This is a screen shot from the diffuse ("basic parameters") section of a VrayMtl: 

![image](https://user-images.githubusercontent.com/23034637/30043638-70b1650a-91ad-11e7-9e81-73ad1aa20beb.png)

There you can see the diffuse amount slider

From the Chaos manpage for the VrayMtl:
https://docs.chaosgroup.com/display/VRAY3MAYA/V-Ray+Material+%7C+VRayMtl

**Diffuse Color** – The diffuse color of the material. Note: the actual diffuse color of the surface also depends on the reflection and refraction colors.

**Amount** – A multiplier for the diffuse color.

**Opacity Map** – Assigns opacity to the material where white is completely opaque and black is completely transparent. You can also assign a map by clicking the check board button. This way you can create a material that has a non-uniform opacity.

...come to think of it, having an opacity color input would be quite useful in the Thunderloom shader for semi-transparent "sheer" materials.

Similarly the reflection color of a VrayMtl in Maya also has a reflection amount slider under it. 

![image](https://user-images.githubusercontent.com/23034637/30043751-223ba84e-91ae-11e7-993f-249864ed0747.png)


-Derek

**Comment by petermcevoy** [comment]
Ah ok! I see! Thank you. I missed that.
A diffuse amount slider would then be good.

**Comment by sharktacos** [comment]
@vidarn @petermcevoy Could this be added to the 1.0 milestone? With a texture map in either the diffuse color or specular color, it's pretty essential for an artist to have an amount slider to modulate this color.

**Comment by petermcevoy** [comment]
Yes, I think that makes sense. Will do.
