### ISSUE TITLE
Arbitrary uv texture lookup on V-Ray Standalone/V-Ray for Maya is not implemented.

### ISSUE THREAD

**Issue by petermcevoy** [vidarn/ThunderLoom#3]
The function tl_eval_texmap_mono_lookup in vray_thunderloom.cpp is not implemeted.
This means that there will be problems when varying yarnsizes non-uniformly, such as with a changing texture. I can't find a way to achieve this sort of lookup using the V-Ray APIs.

See my question on the ChaosGroup forums for more info: https://forums.chaosgroup.com/forum/v-ray-for-maya-forums/v-ray-for-maya-sdk/76255-texture-lookup-with-uv-on-non-bitmap-textures

See the implementation of tl_eval_texmap_mono_lookup in vray3dsMax/3dsMax/Eval.cpp for how it works in V-Ray for 3dsMax.

**Comment by sharktacos** [comment]
May I ask what the purpose of the arbitrary uv texture lookup is? What functionality does this provide?

**Comment by petermcevoy** [comment]
@sharktacos  This is needed to correctly handle yarnsizes which are controlled with a texturemap.

The shader needs to be able to look up the yarnsize of the neighbouring yarns in order to handle the varying yarnsizes correctly, that is, read the texture at uv coordinates that are not the current sampling point.

**Comment by sharktacos** [comment]
Understood, thank you.
