### ISSUE TITLE
ThunderLoom in GI and diffuse render element

### ISSUE THREAD

**Issue by petermcevoy** [vidarn/ThunderLoom#5]
> The shader does not appear in the GI render element (RE) and it is also missing in the diffuse RE. It would be really great if it could appear in the diffuse RE because then one could bake the diffuse WIF pattern into a texture map. This would open up TONS of really great possibilities for look-dev, and so.would be my number 1 wish.

Suggested by Derek Flood.

**Comment by sharktacos** [comment]
@petermcevoy 

Previously it was not possible to connect the diffuse color output of the Thunderloom shader into the diffuse color of a VrayMtl (or to connect it to anything else) in Maya. I'm wondering if this is now possible with this issue #5 being implemented?

Derek

**Comment by petermcevoy** [comment]
@sharktacos hmm. Will take a look.

**Comment by sharktacos** [comment]
@petermcevoy great. FYI, best way to do this in Maya is the Connection Editor or mel. For example
`connectAttr -f VRayThunderLoomMtl1.diffuseColor[0] VRayMtl1.color;`
